pool:
  name: SelfHosted

parameters:
  - name: testType
    displayName: 'Test Type'
    type: string
    default: 'test:report'
    values:
      - test
      - qa:smoke
      - qa:regression
      - qa:negative
      - test:report

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  # Install dependencies
  - script: |
      echo "Installing dependencies..."
      npm install
    displayName: 'Install Dependencies'

  # Run the selected test script dynamically
  - script: |
      echo "Running $(testType) tests..."
      npm run "$(testType)"
    displayName: 'Run $(testType) Tests'
    continueOnError: true

# Publish reports as an artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'reports'  # Path to the reports folder
      artifactName: 'TestReports'
    displayName: 'Publish Test Reports'
    condition: always()